### ISSUE TITLE
Purge plugins and other computer-specific blobs and files from git history.

### ISSUE THREAD

**Issue by Poikilos** [poikilos/r2x_14t#19]
See <https://stackoverflow.com/a/32886427/4541104>:
```
# Make a fresh clone of YOUR_REPO
git clone YOUR_REPO
cd YOUR_REPO

# Create tracking branches of all branches
for remote in `git branch -r | grep -v /HEAD`; do git checkout --track $remote ; done

# Remove DIRECTORY_NAME from all commits, then remove the refs to the old commits
# (repeat these two commands for as many directories that you want to remove)
git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch DIRECTORY_NAME/' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d

# Ensure all old refs are fully removed
rm -Rf .git/logs .git/refs/original

# Perform a garbage collection to remove commits with no refs
git gc --prune=all --aggressive

# Force push all branches to overwrite their history
# (use with caution!)
git push origin --all --force
git push origin --tags --force
```

where DIRECTORY_NAME is:
- [x] config/cura/4.8/plugins
- [x] config/cura/4.9/plugins
- [x] config/cura/4.10/plugins
- [x] config/cura/4.8/cura.log
- [x] config/cura/4.8/cura.log.1
- [x] config/cura/4.9/cura.log
- [x] config/cura/4.10/cura.log

## Statistics
- size before: 56MB
- size after: 28MB

## Additional steps
- [x] (done in 26827f08c6e8025ff801b25b65fbf0f01ef8b826) Remove plugins.json files.
- [x] (done in [3bbbaef](https://github.com/poikilos/r2x_14t/commit/3bbbaef2a905455d67b852dd93a210d102ddc681)) *After* purging in this way, add the files and directories to .gitignore.

**Comment by poikilos** [comment]
done 2022-07-06 (purged from git history and force pushed)
